name: Build and Test Triton (AMD)

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag
        required: true
        type: string
        default: main-windows
      python_minor:
        description: Python minor version
        required: true
        type: string
        default: '12'
      pytest_args:
        description: pytest args
        required: true
        type: string
        default: '-n 0 -s --tb=short'

jobs:
  build-and-test-triton:
    runs-on: triton-windows1
    env:
      PIP_CACHE_DIR: E:\pip-cache
    steps:
      - uses: astral-sh/setup-uv@v5

      - name: Clean caches
        shell: powershell
        run: |
          if (Test-Path -Path ~/.triton) { rm -r ~/.triton }
          if (Test-Path -Path triton-windows/build) { rm -r -Force triton-windows/build }
          if (Test-Path -Path triton-windows/python/build) { rm -r triton-windows/python/build }

      - name: Create venv
        shell: powershell
        run: |
          uv venv .venv-cp3${{ inputs.python_minor }} --python 3.${{ inputs.python_minor }}.10 --clear
          .venv-cp3${{ inputs.python_minor }}\Scripts\activate.ps1
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip

      - name: Build wheel
        shell: powershell
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\Launch-VsDevShell.ps1" -Arch amd64
          .venv-cp3${{ inputs.python_minor }}\Scripts\activate.ps1
          python -m pip install --upgrade cibuildwheel

          git config --global core.autocrlf false
          if (Test-Path -Path triton-windows)
          {
            cd triton-windows
            git add .
            git reset --hard HEAD
            git fetch origin ${{ inputs.git_tag }} --depth 1
            git checkout FETCH_HEAD -B ${{ inputs.git_tag }}
          }
          else
          {
            git clone --branch ${{ inputs.git_tag }} --depth 1 https://github.com/triton-lang/triton-windows.git
            cd triton-windows
          }
          git rev-parse HEAD

          $Env:TRITON_BUILD_PROTON = "0"
          $Env:CIBW_BUILD = "{cp3${{ inputs.python_minor }}-win_amd64,}"
          $Env:CIBW_BUILD_VERBOSITY = "1"
          $Env:CIBW_ENABLE = "cpython-freethreading"
          if (Test-Path -Path wheelhouse) { rm wheelhouse/* }
          if (Test-Path -Path setup.py)
          {
            cibuildwheel .
          }
          else
          {
            cibuildwheel python
          }

      - name: Unit test
        shell: powershell
        run: |
          & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\Launch-VsDevShell.ps1" -Arch amd64
          .venv-cp3${{ inputs.python_minor }}\Scripts\activate.ps1
          python -m pip install --upgrade numpy pytest-xdist pytest-timeout scipy expecttest
          python -m pip install --index-url https://rocm.nightlies.amd.com/v2/gfx110X-all/ torch "rocm[libraries,devel]"
          cd triton-windows/wheelhouse
          python -m pip install $(Get-ChildItem | Select-Object -First 1)
          cd ../python/test/unit
          pytest ${{ inputs.pytest_args }} language/test_core.py
